export const allBuildings = [	
 {
    id: 'kiln',
    name: 'Kiln',
    category: 'Basics',
    cost: { stone: 10 },
    inputs: { stone: 2, coal: 0.2 },
    outputs: { bricks: 1 },
    energyInput: 0,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => true
},
{
    id: 'ironSmelter',
    name: 'Iron Smelter',
    category: 'Basics',
    cost: { bricks: 10 },
    inputs: { ironOre: 2, coal: 0.2 },
    outputs: { ironPlates: 1 },
    energyInput: 0,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'coalPowerPlant',
    name: 'Coal Power Plant',
    category: 'Energy',
    cost: { ironPlates: 15, bricks: 15 },
    inputs: { coal: 0.5 },
    outputs: { coalAsh: 0.1 },
    energyOutput: 16,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: 'Produces 16 energy.'
},
{
    id: 'coalMiner',
    name: 'Coal Miner',
    category: 'Basics',
    cost: { ironPlates: 10, bricks: 10 },
    inputs: {},
    outputs: { coal: 1 },
    energyInput: 1,
    rate: 1,
    minable: true,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'ironMiner',
    name: 'Iron Miner',
    category: 'Basics',
    cost: { ironPlates: 10, bricks: 10 },
    inputs: {},
    outputs: { ironOre: 1 },
    energyInput: 1,
    rate: 1,
    minable: true,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'stoneMiner',
    name: 'Stone Miner',
    category: 'Basics',
    cost: { ironPlates: 10, bricks: 10 },
    inputs: {},
    outputs: { stone: 1 },
    energyInput: 1,
    rate: 1,
    minable: true,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'copperMiner',
    name: 'Copper Miner',
    category: 'Basics',
    cost: { ironPlates: 10, bricks: 10 },
    inputs: {},
    outputs: { copperOre: 1 },
    energyInput: 1,
    rate: 1,
    minable: true,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'copperSmelter',
    name: 'Copper Smelter',
    category: 'Basics',
    cost: { bricks: 15 },
    inputs: { copperOre: 2, coal: 0.2 },
    outputs: { copperPlates: 1 },
    energyInput: 0,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'gearPress',
    name: 'Gear Press',
    category: 'Intermediates',
    cost: { ironPlates: 30, bricks: 25 },
    inputs: { ironPlates: 1 },
    outputs: { gears: 0.5 },
    energyInput: 2,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'cableExtruder',
    name: 'Cable Extruder',
    category: 'Intermediates',
    cost: { gears: 20, bricks: 30 },
    inputs: { copperPlates: 1 },
    outputs: { copperCables: 2 },
    energyInput: 2,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'researchCenter',
    name: 'Research Center',
    category: 'Progress & Expansion',
    cost: { gears: 35, bricks: 50, copperCables: 50 },
    inputs: {},
    outputs: {},
    energyInput: 4,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    description: 'Makes science from this parcel available for research.',
    unlockConditions: () => false,
},
// {
// 	id: 'beltBus',
// 	name: 'Belt Bus',
// 	category: 'Progress & Expansion',
// 	cost: { expansionPoints: 1 },
// 	inputs: {},
// 	outputs: {},
// 	energyInput: 2,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("expansionTech"),
// 	description: 'Move resources between parcels'
// },
// {
// 	id: 'expansionCenter',
// 	name: 'Expansion Center',
// 	category: 'Progress & Expansion',
// 	cost: { ironPlates: 100 },
// 	// inputs: { redScience: 4, bricks: 10, gears: 10 },
// 	// outputs: { expansionPoints: 1 },
// 	inputs: {},
// 	outputs: {},
// 	energyInput: 3,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("expansionTech"),
// 	description: 'Unlocks the ability to add more parcels.'
// },
{
    id: 'steelMill',
    name: 'Steel Mill',
    category: 'Basics',
    cost: { ironPlates: 100, bricks: 400 },
    inputs: { ironPlates: 5 },
    outputs: { steel: 1 },
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'oilWell',
    name: 'Oil Well',
    category: 'Basics',
    cost: { steel: 250, gears: 250, gen1Chip: 75 },
    inputs: {},
    outputs: { oilBarrel: 1 },
    energyInput: 2,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'oilRefinery',
    name: 'Oil Refinery',
    category: 'Basics',
    cost: { steel: 250, gears: 250, gen1Chip: 75 },
    inputs: { oilBarrel: 10 },
    outputs: { petroleumBarrel: 1 },
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'plasticsPlant',
    name: 'Plastics Plant',
    category: 'Intermediates',
    cost: { steel: 500, gears: 500, gen1Chip: 200 },
    inputs: { petroleumBarrel: 1, coal: 0.5 },
    outputs: { plastics: 3 },
    energyInput: 2,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'sulfurPlant',
    name: 'Sulfur Plant',
    category: 'Intermediates',
    cost: { steel: 500, gears: 500, gen1Chip: 200 },
    inputs: { petroleumBarrel: 1 },
    outputs: { sulfur: 2 },
    energyInput: 2,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'remoteConstructionFacility',
    name: 'Construction Hub',
    category: 'Progress & Expansion',
    cost: { gears: 250, gen1Chip: 100 },
    inputs: {},
    outputs: {},
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description:
        'Allows global use of resources from this parcel. -30% Production Rate. +30% Consumption Rate.'
},
{
    id: 'speedBeaconT1',
    name: 'Speed Beacon T1',
    category: 'Beacons',
    cost: { steel: 100, gen2Chip: 100 },
    inputs: {},
    outputs: {},
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: '+2% Production Rate. +2% Consumption Rate.'
},
{
    id: 'productivityBeaconT1',
    name: 'Productivity Beacon T1',
    category: 'Beacons',
    cost: { steel: 100, gen2Chip: 100 },
    inputs: {},
    outputs: {},
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: '+1% Production Rate.'
},
{
    id: 'speedBeaconT2',
    name: 'Speed Beacon T2',
    category: 'Beacons',
    cost: { steel: 350, gen3Chip: 350 },
    inputs: {},
    outputs: {},
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: '+4% Production Rate. +4% Consumption Rate.'
},
{
    id: 'productivityBeaconT2',
    name: 'Productivity Beacon T2',
    category: 'Beacons',
    cost: { steel: 350, gen3Chip: 350 },
    inputs: {},
    outputs: {},
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: '+2% Production Rate.'
},
{
    id: 'speedBeaconT3',
    name: 'Speed Beacon T3',
    category: 'Beacons',
    cost: { steel: 1000, gen4Chip: 1000 },
    inputs: {},
    outputs: {},
    energyInput: 9,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: '+8% Production Rate. +8% Consumption Rate.'
},
{
    id: 'productivityBeaconT3',
    name: 'Productivity Beacon T3',
    category: 'Beacons',
    cost: { steel: 1000, gen4Chip: 1000 },
    inputs: {},
    outputs: {},
    energyInput: 9,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: '+6% Production Rate.'
},
// {
// 	id: 'blueprintLibrary',
// 	name: 'Blueprint Library',
// 	category: 'Progress & Expansion',
// 	cost: { steel: 500, gears: 1500, gen2Chip: 1000 },
// 	inputs: {},
// 	outputs: {},
// 	energyInput: 6,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("blueprintTech"),
// 	description: "Unlocks 'Copy & Paste' in the parcel context menu"
// },
// {
// 	id: 'militaryHQ',
// 	name: 'Military HQ',
// 	category: 'Progress & Expansion',
// 	cost: { ironPlates: 1000, copperCables: 500 },
// 	inputs: {},
// 	outputs: {},
// 	energyInput: 6,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("militaryTech"),
// 	description: 'Makes ammunition from this parcel available for Military Operations'
// },
// {
// 	id: 'standardAmmunitionFactory',
// 	name: 'Ammunition Factory (Standard)',
// 	category: 'Progress & Expansion',
// 	cost: { ironPlates: 1000, gears: 500 },
// 	inputs: { ironPlates: 1, copperPlates: 3 },
// 	outputs: { standardAmmunition: 5 },
// 	energyInput: 6,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("militaryTech"),
// },
// {
// 	id: 'armorPenetratingAmmunitionFactory',
// 	name: 'Ammunition Factory (Armor Pen)',
// 	category: 'Progress & Expansion',
// 	cost: { steel: 1000, gears: 500, gen1Chip: 500 },
// 	inputs: { standardAmmunition: 25, steel: 1, copperPlates: 2 },
// 	outputs: { armorPenetratingAmmunition: 5 },
// 	energyInput: 12,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("militaryTech2"),
// },
// {
// 	id: 'piercingAmmunitionFactory',
// 	name: 'Ammunition Factory (Piercing)',
// 	category: 'Progress & Expansion',
// 	cost: { steel: 10000, gears: 10000, gen3Chip: 5000 },
// 	inputs: { armorPenetratingAmmunition: 20, steel: 1, copperPlates: 1 },
// 	outputs: { piercingAmmunition: 5 },
// 	energyInput: 18,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("militaryTech3"),
// },
// {
// 	id: 'trainStation',
// 	name: 'Train Station',
// 	category: 'Progress & Expansion',
// 	cost: { steel: 100, copperCables: 100, gen1Chip: 50 },
// 	inputs: {},
// 	outputs: {},
// 	energyInput: 8,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("trains"),
// },
// {
// 	id: 'railFactory',
// 	name: 'Rail Factory',
// 	category: 'Intermediates',
// 	cost: { steel: 150, bricks: 150 },
// 	inputs: { stone: 1, steel: 1 },
// 	outputs: { rail: 5 },
// 	energyInput: 4,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("trains"),
// },
// {
// 	id: 'turretFactory',
// 	name: 'Turret Factory',
// 	category: 'Intermediates',
// 	cost: { steel: 150, bricks: 150 },
// 	inputs: { gears: 75, steel: 25, bricks: 25 },
// 	outputs: { turret: 1 },
// 	energyInput: 6,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("militaryTech"),
// },
// {
// 	id: 'wallFactory',
// 	name: 'Wall Factory',
// 	category: 'Intermediates',
// 	cost: { steel: 150, bricks: 150 },
// 	inputs: { ironPlates: 5, bricks: 50 },
// 	outputs: { wall: 1 },
// 	energyInput: 6,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(_research).completed.has("militaryTech"),
// },
{
    id: 'redScienceLab',
    name: 'Red Science Laboratory',
    category: 'Progress & Expansion',
    cost: { gears: 50, bricks: 50 },
    inputs: { copperCables: 5, gears: 2 },
    outputs: { redScience: 1 },
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'greenScienceLab',
    name: 'Green Science Laboratory',
    category: 'Progress & Expansion',
    cost: { gen1Chip: 80, steel: 180, bricks: 160 },
    inputs: { copperCables: 12, gen1Chip: 4 },
    outputs: { greenScience: 1 },
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
// {
// 	id: 'darkScienceLab',
// 	name: 'Dark Science Laboratory',
// 	category: 'Progress & Expansion',
// 	cost: { gen2Chip: 250, copperCables: 250, gears: 250, bricks: 250 },
// 	inputs: { standardAmmunition: 80, turret: 1, wall: 3 },
// 	outputs: { darkScience: 1 },
// 	energyInput: 3,
// 	rate: 1,
// 	minable: false,
// 	productionRateModifier: 0,
// 	consumptionRateModifier: 0,
// 	productionModifierSources: {},
// 	consumptionModifierSources: {},
// 	unlockConditions: () => get(parcels).some((parcel) => parcel.buildings.greenScienceLab > 0)
// },
{
    id: 'blueScienceLab',
    name: 'Blue Science Laboratory',
    category: 'Progress & Expansion',
    cost: { gen2Chip: 250, steel: 250, bricks: 250 },
    inputs: { sulfur: 8, gen2Chip: 4 },
    outputs: { blueScience: 1 },
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'purpleScienceLab',
    name: 'Purple Science Laboratory',
    category: 'Progress & Expansion',
    cost: { gen3Chip: 250, steel: 250, bricks: 250 },
    inputs: { steel: 3, gen3Chip: 2, gen1Chip: 4 },
    outputs: { purpleScience: 1 },
    energyInput: 3,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'yellowScienceLab',
    name: 'Yellow Science Laboratory',
    category: 'Progress & Expansion',
    cost: { gen4Chip: 250, steel: 250, bricks: 250 },
    inputs: { gen4Chip: 2, gen2Chip: 4 },
    outputs: { yellowScience: 1 },
    energyInput: 3,
    rate: 1,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    minable: false,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
},
{
    id: 'batteryFactory',
    name: 'Battery Factory',
    category: 'Intermediates',
    cost: { steel: 500, bricks: 500, gen1Chip: 500 },
    inputs: { ironPlates: 1, copperPlates: 1, sulfur: 1 },
    outputs: { battery: 1 },
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'solarBatteryArray',
    name: 'Solar & Battery Array',
    category: 'Energy',
    cost: { steel: 100, copperCables: 100, gen1Chip: 50, battery: 50 },
    inputs: {},
    outputs: {},
    energyOutput: 16,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    description: 'Produces 16 energy.',
    unlockConditions: () => false
},
{
    id: 'fuelProcessingFacility',
    name: 'Fuel Processing Facility',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen5Chip: 500 },
    inputs: { petroleumBarrel: 10, coal: 10 },
    outputs: { fuelCell: 1 },
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'LDSFactory',
    name: 'LDS Factory',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen5Chip: 500 },
    inputs: { copperPlates: 20, plastics: 5, steel: 2 },
    outputs: { lightDensityStructures: 1 },
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'rocketControlUnitFactory',
    name: 'Rocket Control Unit Factory',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen5Chip: 500 },
    inputs: { gen5Chip: 1, gen4Chip: 5, gen3Chip: 10, gen2Chip: 25, gen1Chip: 50 },
    outputs: { rocketControlUnit: 1 },
    energyInput: 6,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'rocketLaunchPad',
    name: 'Rocket Launch Pad',
    category: 'Progress & Expansion',
    cost: { steel: 5000, bricks: 5000, gen5Chip: 500 },
    inputs: { satelite: 1, rocketParts: 100 },
    outputs: { whiteScience: 1000 },
    energyInput: 16,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'rocketPartAssembly',
    name: 'Rocket Part Assembly',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen5Chip: 500 },
    inputs: { fuelCell: 4, lightDensityStructures: 4, rocketControlUnit: 4 },
    outputs: { rocketParts: 1 },
    energyInput: 20,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'sateliteAssembly',
    name: 'Satelite Assembly',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen5Chip: 500 },
    inputs: {
        copperPlates: 300,
        ironPlates: 180,
        plastics: 300,
        gen5Chip: 100,
        fuelCell: 50,
        steel: 300
    },
    outputs: { satelite: 1 },
    energyInput: 20,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'productionChallengePlant',
    name: 'Production Challenge Plant',
    category: 'Progress & Expansion',
    cost: { steel: 1000, bricks: 250 },
    inputs: {},
    outputs: {},
    energyInput: 12,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'quartzRefinery',
    name: 'Quartz Refinery',
    category: 'Intermediates',
    cost: { steel: 150, bricks: 250 },
    inputs: { stone: 3 },
    outputs: { quartz: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'siliconFurnace',
    name: 'Silicon Furnace',
    category: 'Intermediates',
    cost: { steel: 150, bricks: 250 },
    inputs: { quartz: 1, coal: 0.25 },
    outputs: { silicon: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'bauxiteMiner',
    name: 'Bauxite Miner',
    category: 'Intermediates',
    cost: { steel: 150, bricks: 250 },
    inputs: {},
    outputs: { bauxiteOre: 10 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'aluminiumSmelter',
    name: 'Aluminium Smelter',
    category: 'Intermediates',
    cost: { steel: 250, bricks: 150 },
    inputs: { bauxiteOre: 5, coal: 1 },
    outputs: { aluminium: 0.5 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'gen1ChipPlant',
    name: 'Gen 1 Chip Plant',
    category: 'Intermediates',
    cost: { steel: 350, bricks: 350 },
    inputs: { silicon: 2, copperCables: 3, aluminium: 0.5 },
    outputs: { gen1Chip: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'bioreactor',
    name: 'Bioreactor',
    category: 'Intermediates',
    cost: { steel: 150, bricks: 150, gen1Chip: 50 }, // TODO: Add Biomatter as a cost --> Biomatter is acquired by killing aliens.
    inputs: {},
    outputs: { oxygen: 0.1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'oxidationFurnace',
    name: 'Oxidation Furnace',
    category: 'Intermediates',
    cost: { steel: 1000, bricks: 1000, gen1Chip: 500 },
    inputs: { silicon: 1, oxygen: 2 },
    outputs: { siliconDioxide: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'gen2ChipPlant',
    name: 'Gen 2 Chip Plant',
    category: 'Intermediates',
    cost: { steel: 500, bricks: 500, gen1Chip: 500 },
    inputs: { siliconDioxide: 1, plastics: 1 },
    outputs: { gen2Chip: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'phenolicResinPlant',
    name: 'Phenolic Resin Plant',
    category: 'Intermediates',
    cost: { steel: 1000, bricks: 1000, gen1Chip: 500 },
    inputs: { petroleumBarrel: 1, coal: 4, coalAsh: 2 },
    outputs: { phenolicResin: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'lowDepositionChamber',
    name: 'Low Deposition Chamber',
    category: 'Intermediates',
    cost: { steel: 1000, bricks: 1000, gen2Chip: 1000 },
    inputs: { silicon: 1, oxygen: 1 },
    outputs: { lowkDielectric: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'germaniumRefinery',
    name: 'Germanium Refinery',
    category: 'Intermediates',
    cost: { steel: 500, bricks: 500, gen2Chip: 250 },
    inputs: { coalAsh: 0.6 },
    outputs: { germanium: 0.1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'alloyFurnace',
    name: 'SiGe Furnace',
    category: 'Intermediates',
    cost: { steel: 500, bricks: 500, gen2Chip: 250 },
    inputs: { silicon: 1, germanium: 1 },
    outputs: { siliconGermanium: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'highGradeSmelter',
    name: 'High-Grade Smelter',
    category: 'Intermediates',
    cost: { steel: 1500, bricks: 1500, gen2Chip: 500 },
    // inputs: { hgCopperOre: 1 },
    inputs: { copperOre: 20, coal: 4 },
    outputs: { hgCopperPlate: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'gen3ChipPlant',
    name: 'Gen 3 Chip Plant',
    category: 'Intermediates',
    cost: { steel: 1500, bricks: 1500, gen2Chip: 1000 },
    inputs: { lowkDielectric: 1, siliconGermanium: 0.5, hgCopperPlate: 0.5, phenolicResin: 1 },
    outputs: { gen3Chip: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'hafniumMine',
    name: 'Hafnium Mine',
    category: 'Intermediates',
    cost: { steel: 500, bricks: 500, gen3Chip: 150 },
    inputs: {},
    outputs: { hafnium: 0.1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'advancedDepositionChamber',
    name: 'Advanced Deposition Chamber',
    category: 'Intermediates',
    cost: { steel: 2500, bricks: 2500, gen3Chip: 1000 },
    inputs: { hafnium: 1, siliconDioxide: 1, silicon: 2 },
    outputs: { highkDielectric: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'metalGatePlant',
    name: 'Metal Gate Plant',
    category: 'Intermediates',
    cost: { steel: 2500, bricks: 2500, gen3Chip: 1000 },
    inputs: { hafnium: 2, silicon: 4 },
    outputs: { metalGate: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'gen4ChipPlant',
    name: 'Gen 4 Chip Plant',
    category: 'Intermediates',
    cost: { steel: 2500, bricks: 2500, gen3Chip: 1000 },
    inputs: { siliconGermanium: 1, highkDielectric: 1, metalGate: 1, phenolicResin: 1 },
    outputs: { gen4Chip: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'grapheneLab',
    name: 'Graphene Lab',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen4Chip: 800 },
    inputs: { silicon: 1, coal: 1, coalAsh: 0.1 },
    outputs: { graphene: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'hafniumDisulfidePlant',
    name: 'Hafnium-Disulfide Plant',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen4Chip: 800 },
    inputs: { hafnium: 1, sulfur: 2 },
    outputs: { hafniumDisulfide: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'nanowireLab',
    name: 'Nanowire Lab',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen4Chip: 800 },
    inputs: { hafnium: 1, siliconGermanium: 1, oxygen: 1 },
    outputs: { nanowires: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'apMateriallLab',
    name: 'AP-Material Lab',
    category: 'Intermediates',
    cost: { steel: 5000, bricks: 5000, gen4Chip: 800 },
    inputs: { hgCopperPlate: 1, phenolicResin: 1, quartz: 1 },
    outputs: { apMaterial: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'gen5ChipPlant',
    name: 'Gen 5 Chip Plant',
    category: 'Intermediates',
    cost: { steel: 150, bricks: 150 },
    inputs: { graphene: 3, hafniumDisulfide: 2, nanowires: 2, apMaterial: 2 },
    outputs: { gen5Chip: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'droneFactory',
    name: 'Drone Factory',
    category: 'Intermediates',
    cost: { steel: 150, bricks: 150 },
    inputs: { gen2Chip: 1, gen1Chip: 1, gears: 2, copperCables: 8 },
    outputs: { drone: 1 },
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false
},
{
    id: 'dronePort',
    name: 'Drone Port',
    category: 'Progress & Expansion',
    cost: { steel: 1500, bricks: 1500, drone: 100 },
    inputs: {},
    outputs: {},
    energyInput: 8,
    rate: 1,
    minable: false,
    productionRateModifier: 0,
    consumptionRateModifier: 0,
    productionModifierSources: {},
    consumptionModifierSources: {},
    unlockConditions: () => false,
    description: 'Increases Task Execution Speed by +2 Tasks / Minute.'
}
];